###
GET http://35.174.109.220:8080/auth/chat/quit/6010b34e-10fc-4022-9f94-47ba98056d0c
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyNDQyNjYzNDEwIiwibmFtZSI6IuuLpOydgCIsImF1dGgiOiJST0xFX1VTRVIifQ.FmLciZy1afVgp5qs7NShDyLwK_K15weiNtMSAmuPCRg

# ###
# POST http://35.174.109.220:8080/auth/chat/quit/68966c18-7394-4745-a7bb-aa9cbe7bb316
# Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyNDQyNjYzNDEwIiwibmFtZSI6IuuLpOydgCIsImF1dGgiOiJST0xFX1VTRVIifQ.FmLciZy1afVgp5qs7NShDyLwK_K15weiNtMSAmuPCRg
# Content-Type: application/json
# {
#     "name" : "ssdasd",
# }


###
GET http://35.174.109.220:8080/auth/chat/enter/b0dee45e-b975-4599-9a15-36aff899c085
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyNDQyNjYzNDEwIiwibmFtZSI6IuuLpOydgCIsImF1dGgiOiJST0xFX1VTRVIifQ.FmLciZy1afVgp5qs7NShDyLwK_K15weiNtMSAmuPCRg